apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - gslb.yaml
patches:
  - path: runtime-patch.yaml
images:
  - name: ghcr.io/kryputh/stellar-marketpay-backend
    newTag: replace-with-immutable-tag
  - name: ghcr.io/kryputh/stellar-marketpay-frontend
    newTag: replace-with-immutable-tag
